env: sc2

env_args:
  continuing_episode: False
  difficulty: "7"
  game_version: null
  map_name: "8m"
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False

test_greedy: True
test_nepisode: 500
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2000000
#run_mode: "Train"

#checkpoint_path: "xxx"

# Start (code for test). if train: comment followings; elif test: uncomment.
#run_mode: "Test"
#batch_size_run: 500
#save_model: False
#save_replay: False

# attack
#need_attack: False
#att_size: 1
#noise_w: 1

# patch
#need_patch: True
#need_collect: True
#patch_budget: 50
##diff_th: 1   # 1c3s5z.
#diff_th: 3   # 27m_vs_30m. 3
##diff_th: 2   # 8m.
#ep_reward_th: 19.5

#masker_checkpoint_path: "xxx"